### ISSUE TITLE
Segmentated file naming

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/difumo_segmentation#2]
After having a think I would suggest to name the directory with the original dimensions, so it's easier to refer back to the original atlas.
Right now it's difficult to find out which original difumo atlas was the extracted version derived from.
Two different resolution can have different extraction results.
They ended up in different directories. 

I would revise the directories like this:
```
processed/64/2mm/maps.nii.gz
processed/64/2mm/labels.csv
processed/64/3mm/maps.nii.gz
processed/64/3mm/labels.csv
```
In the labels file, what is missing now is the original difumo dimension index. 

I can do a PR (or just get edit access to this repo?)

One place I think we can draw inspiration from is the templateflow:
https://github.com/templateflow/tpl-MNI152NLin2009cAsym
However I won't make this a priority for now. Just a thought.

**Comment by ltetrel** [comment]
I had the exact same feeling, still we need to keep the number of extracted dimension.
That is quick to change so I can do it.

On templateflow this is definitively a good idea, once we generated the extracted atlas.
