### ISSUE TITLE
Performance of RegionExtractor

### ISSUE THREAD

**Issue by htwangtw** [SIMEXP/difumo_segmentation#3]
This is an upstream issue but just want to make a note here and move on with the most pragmatic way:
The region extractor doesn't scale to atlas with higher number of dimensions very well.
On my local machine it can only handle 64 and 128 dimensions. 
Testing out the resource requirement isn't exactly the most efficient use of time given the aim of the project.
Would it be fine to settle for using 64 and 128 dimensions to generate connectomes? 
cc @pbellec

**Comment by ltetrel** [comment]
My laptop was also not able to handle those. As discussed during the meeting, we will have no choice to use HPC to generate the atlas and save it somewhere. 
There could be some optimization to reduce mem consumption but I don't think that it is necessary to put too much time on this.

**Comment by htwangtw** [comment]
Let's put it on a HPC and not bother with optimising the performance then
